### ISSUE TITLE
Variable definition problem

### ISSUE THREAD

**Issue by BeautiLu** [negar-foroutan/multiLMs-lang-neutral-subnets#1]
Code error message: 
These two variables are defined after the reference.
"multiLMs-lang-neutral-subnets\helpers\data_processor.py", line 47, in __init__
    num_examples = int(len(tokenized_text)/ block_size)
UnboundLocalError: local variable 'block_size' referenced before assignment

"multiLMs-lang-neutral-subnets\helpers\data_processor.py", line 67, in __init__
    logger.info("Saving features into cached file %s", cached_features_file)
UnboundLocalError: local variable 'cached_features_file' referenced before assignment
![image](https://github.com/negar-foroutan/multiLMs-lang-neutral-subnets/assets/99852603/782a992a-a82c-4b2f-9dc6-2c66c7227df5)

**Comment by negar-foroutan** [comment]
Hi, thanks for pointing out the issue. It's already resolved!
