### ISSUE TITLE
Inquiry about Function Dependency in analysis_tools.py

### ISSUE THREAD

**Issue by BeautiLu** [negar-foroutan/multiLMs-lang-neutral-subnets#3]
Could you please clarify whether the get_mbert_mask_ones_overlap(mask_list) function is capable of directly computing the similarity between two subnetworks without relying on other functions? (Because I found other functions in this file that I didn't use, I was a little confused)
If it does depend on other functions, could you kindly provide some insight into which functions are necessary for its operation?
![image](https://github.com/negar-foroutan/multiLMs-lang-neutral-subnets/assets/99852603/3375d48e-e16c-4fe1-975c-eb96ec4c8a00)
![image](https://github.com/negar-foroutan/multiLMs-lang-neutral-subnets/assets/99852603/bc97eee3-c555-4405-ab64-c0821b52bb70)

**Comment by negar-foroutan** [comment]
Hi, 
You can use this function directly to compute the similarity between two subnetworks (i.e., where the mask values are 1 in both), and it doesn't depend on other functions. 
However, If you want to compute the sparsity overlap (considering both 1s and 0s), you need to use `mask_sparsity_overlap`.

**Comment by BeautiLu** [comment]
Thank you！！！
